### ISSUE TITLE
time bikeshare problem

### ISSUE THREAD

**Issue by Ro0o** [NidalShater/My-Udacity-Bikeshare-Project#1]
df['hour'] = df['Start Time'].dt.hour
    popular_hour = df['hour'].mode()[0]
        if popular_hour <= 12 :
            popular_hour = print('Most Common Hour:'popular_hour , 'AM')
        else :
            popular_hour = popular_hour - 12
            print('Most Common Hour:', popular_hour , 'PM')

I'm trying to make the hour appear in am, pm mode in python  but this error appears 

File "bikeshare.py", line 95
    if 'popular_hour' <= 12 :
    ^
IndentationError: unexpected indent

what should I do?

**Comment by NidalShater** [comment]
@Ro0o, you have as the compiler reported an IndentationError, which means you need to add proper tabs, also you have an error (you are missing an ',') in this line `popular_hour = print('Most Common Hour:'popular_hour , 'AM')`

The Final Code should be something like this: 
```
popular_hour = 6
if popular_hour <= 12 :
    popular_hour = print('Most Common Hour:',popular_hour , 'AM')
else :
    popular_hour = popular_hour - 12
    print('Most Common Hour:', popular_hour , 'PM')
```
